default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  encoding: utf8mb4
  database: audit_sys_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  <<: *default
  encoding: utf8mb4
  database: audit_sys_test
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  port: '<%= ENV["DB_PORT"] %>'
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  database: audit_sys_production
  username: <%= ENV["DB_USER"] %>
  password: '<%= ENV["DB_PW"] %>'
  socket: /var/lib/mysql/mysql.sock
